package com.xabit.utility;

public enum Field {
	ACCOUNT_NAME,
	ACCOUNT_SITE,
	AMOUNT, CLOSED,
	CLOSE_DATE,
	CREATED_BY_ALIAS,
	CREATED_DATE,
	CURRENT_GENERATOR,
	DELIVERY_INSTALLATION_STATUS,
	EXPECTED_REVENUE,
	FISCAL_PERIOD,
	FISCAL_QUARTER, 
	FISCAL_YEAR,
	FORECAST_CATEGORY,
	LAST_ACTIVITY,
	LAST_MODIFIED_BY_ALIAS,
	LAST_MODIFIED_DATE,
	LAST_STAGE_CHANGE_DATE,
	LEAD_SOURCE,
	MAIN_COMPETITOR,
	NEXT_STEP,
	OPPORTUNITY_NAME,
	OPPORTUNITY_OWNER_ALIAS,
	ORDER_NUMBER,
	OWNER_FIRST_NAME,
	OWNER_FULL_NAME,
	OWNER_LAST_NAME,
	PRIVATE,
	PROBABILITY,
	PUSH_COUNT,
	QUANTITY,
	STAGE, TOPICS,
	TRACKING_NUMBER,
	TYPE, WON;

	

}
