package com.xabit.utility;

public enum Industry {
	AGRICULTURE, APPAREL, BANKING, BIOTECHNOLOGY, CHEMICALS, COMMUNICATIONS,CONSTRUCTION,CONSULTING, EDUCATION ,ELECTRONICS, ENERGY, ENGINEERING, ENTERTAINMENT, ENVIRONMENTAL, FINANCE, FOOD_AND_BEVERAGE, GOVERNMENT, HEALTHCARE, HOSPITALITY, INSURANCE, MACHINERY, MANUFACTURING, MEDIA,NOT_FOR_PROFIT, RECREATION,RETAIL,SHIPPING, TECHNOLOGY , TELECOMMUNICATIONS, TRANSPORTATION, UTILITIES, OTHER
}
