package com.xabit.utility;

public enum Stagename {
	PROSPECTING, QUALIFICATION,NEEDS_ANALYSIS, VALUE_PROPOSITION, DECISION_MAKERS, PERCEPTION_ANALYSIS, PROPOSAL_OR_PRICE_QUOTE,NEGOTIATION_OR_REVIEW, CLOSED_WON,CLOSED_LOST
}
